// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebGestionAppro.Data;

#nullable disable

namespace WebGestionAppro.Migrations
{
    [DbContext(typeof(GesApproDbContext))]
    [Migration("20251204103002_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebGestionAppro.Models.Approvisionnement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateApprovisionnement")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observations")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Approvisionnements");
                });

            modelBuilder.Entity("WebGestionAppro.Models.ApprovisionnementArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovisionnementId")
                        .HasColumnType("int");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovisionnementId");

                    b.HasIndex("ArticleId");

                    b.ToTable("ApprovisionnementArticles");
                });

            modelBuilder.Entity("WebGestionAppro.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockActuel")
                        .HasColumnType("int");

                    b.Property<string>("Unite")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreation = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tissu 100% coton blanc de qualité supérieure",
                            Nom = "Tissu Coton Blanc",
                            PrixUnitaire = 2500m,
                            StockActuel = 150,
                            Unite = "mètre"
                        },
                        new
                        {
                            Id = 2,
                            DateCreation = new DateTime(2023, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tissu wax traditionnel avec motifs",
                            Nom = "Tissu Wax Multicolore",
                            PrixUnitaire = 4500m,
                            StockActuel = 80,
                            Unite = "mètre"
                        },
                        new
                        {
                            Id = 3,
                            DateCreation = new DateTime(2023, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bobine de fil noir 500m",
                            Nom = "Fil à coudre Noir",
                            PrixUnitaire = 500m,
                            StockActuel = 200,
                            Unite = "bobine"
                        },
                        new
                        {
                            Id = 4,
                            DateCreation = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lot de 100 boutons plastique blancs",
                            Nom = "Boutons Plastique",
                            PrixUnitaire = 1000m,
                            StockActuel = 50,
                            Unite = "lot"
                        },
                        new
                        {
                            Id = 5,
                            DateCreation = new DateTime(2023, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fermeture éclair métal 20cm",
                            Nom = "Fermeture Éclair 20cm",
                            PrixUnitaire = 300m,
                            StockActuel = 120,
                            Unite = "pièce"
                        });
                });

            modelBuilder.Entity("WebGestionAppro.Models.Fournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Fournisseurs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "Zone Industrielle, Dakar",
                            DateCreation = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@textilesdakar.sn",
                            Nom = "Textiles Dakar SARL",
                            Telephone = "+221 33 123 4567"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "Rue 10, Dakar",
                            DateCreation = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@merceriecentrale.sn",
                            Nom = "Mercerie Centrale",
                            Telephone = "+221 33 234 5678"
                        },
                        new
                        {
                            Id = 3,
                            Adresse = "Avenue Lamine Gueye, Dakar",
                            DateCreation = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@tissuspremium.sn",
                            Nom = "Tissus Premium",
                            Telephone = "+221 33 345 6789"
                        });
                });

            modelBuilder.Entity("WebGestionAppro.Models.Approvisionnement", b =>
                {
                    b.HasOne("WebGestionAppro.Models.Fournisseur", "Fournisseur")
                        .WithMany("Approvisionnements")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("WebGestionAppro.Models.ApprovisionnementArticle", b =>
                {
                    b.HasOne("WebGestionAppro.Models.Approvisionnement", "Approvisionnement")
                        .WithMany("ApprovisionnementArticles")
                        .HasForeignKey("ApprovisionnementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebGestionAppro.Models.Article", "Article")
                        .WithMany("ApprovisionnementArticles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approvisionnement");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("WebGestionAppro.Models.Approvisionnement", b =>
                {
                    b.Navigation("ApprovisionnementArticles");
                });

            modelBuilder.Entity("WebGestionAppro.Models.Article", b =>
                {
                    b.Navigation("ApprovisionnementArticles");
                });

            modelBuilder.Entity("WebGestionAppro.Models.Fournisseur", b =>
                {
                    b.Navigation("Approvisionnements");
                });
#pragma warning restore 612, 618
        }
    }
}
